version: '3'

volumes:
  pg_data:
  frontend_static:
  backend_static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  frontend:
    image: hourvari/foodgram_frontend:latest
    env_file: .env
    volumes:
      - frontend_static:/frontend_static

  backend:
    image: hourvari/foodgram_backend:latest
    env_file: .env
    volumes:
      - backend_static:/backend_static
      - media:/app/media
    depends_on:
      - db

  gateway:
    build: ./gateway/
    env_file: .env
    volumes:
      - frontend_static:/frontend_static
      - backend_static:/backend_static
      - media:/media/
    ports:
      - "8000:80"
    depends_on:
      - backend
      - frontend